CCS_COMPILER	= ccsc
CCS_SOURCE		= main.c
CCS_FLAGS_NBL	= +FH +Y9 -L -A -E -M -P -J -D
CCS_FLAGS_WBL	= $(CCS_FLAGS_NBL) +GWBOOTLOADER="true"
CCS_FLAGS_DEV	= +GDEV_PAYLOAD="true"
ZIP				= zip
CLEAN_FILES		= *.err *.esym *.hex *.zip

GITHEAD := $(shell cd PL3 && git rev-parse HEAD && cd ..)

all:
		rm -f $(CLEAN_FILES)

		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW341="true" $(CCS_SOURCE)

		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW341="true" $(CCS_SOURCE)

		$(ZIP) "PSGrooPIC_PL3_$(GITHEAD)" *.hex

dev:
		rm -f $(CLEAN_FILES)

		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW341="true" $(CCS_SOURCE)

		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW341="true" $(CCS_SOURCE)

		$(ZIP) "PSGrooPIC_PL3_DEV_$(GITHEAD)" *.hex

clean: 
		rm -f $(CLEAN_FILES)