CCS_COMPILER	= ccsc
CCS_SOURCE		= main.c
CCS_FLAGS_NBL	= +FH +Y9 -L -A -E -M -P -J -D
CCS_FLAGS_WBL	= $(CCS_FLAGS_NBL) +GWBOOTLOADER="true"
CCS_FLAGS_DEV	= +GDEV_PAYLOAD="true"
ZIP				= zip
CLEAN_FILES		= *.err *.esym *.hex *.zip

DEFAULT_PAYLOAD	= default_payload
DEV_PAYLOAD		= payload_dev
PAYLOAD_DIR		= PL3

GITHEAD = $(shell cd $(PAYLOAD_DIR) && git rev-parse HEAD && cd ..)

B2HTARGET = $(CURDIR)/tools/bin2header

all:
		#Make bin2header.
		$(MAKE) -C tools

		#Make PL3.
		$(MAKE) -C $(PAYLOAD_DIR)

		#Make custom Payload.
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_3_01.bin $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_pic_3_01.h $(DEFAULT_PAYLOAD)_3_01
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_3_10.bin $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_pic_3_10.h $(DEFAULT_PAYLOAD)_3_10
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_3_15.bin $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_pic_3_15.h $(DEFAULT_PAYLOAD)_3_15
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_3_41.bin $(PAYLOAD_DIR)/$(DEFAULT_PAYLOAD)_pic_3_41.h $(DEFAULT_PAYLOAD)_3_41

		#HEX with bootloader.
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW341="true" $(CCS_SOURCE)

		#HEX without bootloader.
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW341="true" $(CCS_SOURCE)

		#Zip all HEX.
		$(ZIP) "PSGrooPIC_PL3_$(GITHEAD)" *.hex

dev:
		#Make bin2header.
		$(MAKE) -C tools

		#Make PL3.
		$(MAKE) -C $(PAYLOAD_DIR)

		#Make custom Payload.
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_3_01.bin $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_pic_3_01.h $(DEV_PAYLOAD)_3_01
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_3_10.bin $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_pic_3_10.h $(DEV_PAYLOAD)_3_10
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_3_15.bin $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_pic_3_15.h $(DEV_PAYLOAD)_3_15
		$(B2HTARGET) $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_3_41.bin $(PAYLOAD_DIR)/$(DEV_PAYLOAD)_pic_3_41.h $(DEV_PAYLOAD)_3_41

		#HEX with bootloader.
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_WBL) $(CCS_FLAGS_DEV) +GFW341="true" $(CCS_SOURCE)

		#HEX without bootloader.
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW301="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW310="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW315="true" $(CCS_SOURCE)
		$(CCS_COMPILER) $(CCS_FLAGS_NBL) $(CCS_FLAGS_DEV) +GFW341="true" $(CCS_SOURCE)

		#Zip all HEX.
		$(ZIP) "PSGrooPIC_PL3_DEV_$(GITHEAD)" *.hex

clean: 
		#Clean files.
		rm -f $(CLEAN_FILES)

		#Remove compilations.
		$(MAKE) -C PL3/ clean
		$(MAKE) -C tools/ clean