CCS_COMPILER	= ccsc
CCS_SOURCE		= main.c
CCS_FLAGS_WBL	= +FH +Y9 -L -A -E -M -P -J -D +GWBOOTLOADER="true"
CCS_FLAGS_NBL	= +FH +Y9 -L -A -E -M -P -J -D

all:
	$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW301="true" $(CCS_SOURCE)
	$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW310="true" $(CCS_SOURCE)
	$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW315="true" $(CCS_SOURCE)
	$(CCS_COMPILER) $(CCS_FLAGS_WBL) +GFW341="true" $(CCS_SOURCE)

	$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW301="true" $(CCS_SOURCE)
	$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW310="true" $(CCS_SOURCE)
	$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW315="true" $(CCS_SOURCE)
	$(CCS_COMPILER) $(CCS_FLAGS_NBL) +GFW341="true" $(CCS_SOURCE)

clean: 
		rm -f *.err *.esym *.hex